export const SET_WEATHER_DATA = "SET_WEATHER_DATA";
export const SET_IMAGE_DATA = "SET_IMAGE_DATA";
export const SET_LOADING_IMAGE_DATA = "SET_LOADING_IMAGE_DATA";
export const SET_WEATHER_SELECTED_DAY = "SET_WEATHER_SELECTED_DAY";
export const SET_WEATHER_SELECTED_DAY_LOADING =
  "SET_WEATHER_SELECTED_DAY_LOADING";
export const SET_LOADING_SELECED_DATA = "SET_LOADING_SELECED_DATA";
export const SET_ERROR_IMAGE = "SET_ERROR_IMAGE";
export const ADD_COUNTRY_FAVORITES = "ADD_COUNTRY_FAVORITES";
export const REMOTE_COUNTRY_FAVORITES = "REMOTE_COUNTRY_FAVORITES";
export const ERROR_WEATHER = "ERROR_WEATHER";
